env:
  browser: true
  es6: true
# extends: 'eslint:recommended'
extends: 'airbnb'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/no-multi-comp:
    - off
  react/prefer-stateless-function:
    - warn
  react/prop-types:
    - warn
  arrow-body-style:
    - warn
    - as-needed  # default